
server:
    port: 8090
spring:
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: sa
    password: 123321
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
  liquibase:
    change-log: classpath:/db/changelog/master.yml
    drop-first: true
