
server:
    port: 8090
spring:
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: sa
    password: 123321
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yml
#    drop-first: true
#  mvc:
#    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
#  jpa:
#    hibernate:
#      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 465
    username: "jobsearchnoreply149@gmail.com"
    password: "ulja vaxg xkup uhoa"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
logging:
  file:
    name: logs/app.log
  level:
    root: WARN






